### PR TITLE
Fix wheel mouse 3rd button bit

### PR DESCRIPTION
**Pull request by sweetlilmre**
Changed the wheel mouse 3rd button bit from 0x20 to 0x10 as per: https://sourceforge.net/p/cutemouse/trunk/ci/master/tree/cutemouse/PROTOCOL.TXT

### CODE REVIEW

**Comment by LimeProgramming** [comment]
I genuinely don't remember how this works, so I'll give it a test on the weekend, power is going to be spotty from tomorrow to weekend, but it looks about right looking at the protocol you linked. 
Considering it works as is, probably both bits are checked by the driver but better to stick to the actual protocol as it's supposed to me, might double check that with the ctmouse source code if I can figure that out again. 

You asked before about how to mod ctmouse, you need to modify the serial latch divisor, It's set to 96 in two places, every halving of 96 (which is in Hex) doubles the baud rate. The hard part with it isn't the code but compiling the code, you need specific old versions of the compilers. The Win3.X and Win9X drivers have the same mod, just edited in HxD.

**Comment by sweetlilmre** [comment]
Hey!

Spotty power? Sounds like RSA! Had solar installed which helps. One of my first questions was: "Can I solder while on backup?" :)

This might help with the compilation of cutemouse: [https://github.com/davidebreso/ctmouse](https://github.com/davidebreso/ctmouse)

Haven't had a chance to test it out yet though.

**Comment by sweetlilmre** [comment]
OK that wasn't too bad. 

*   Used WSL
*   Got, compiled and installed JWasm from here: [https://github.com/Baron-von-Riedesel/JWasm](https://github.com/Baron-von-Riedesel/JWasm)
*   Used [https://github.com/davidebreso/ctmouse](https://github.com/davidebreso/ctmouse) port
*   Had to change some include paths in ctmouse.asm as they were incorrectly cased (or the files were, but this was easier)

No idea if it actually works though :)

**Comment by LimeProgramming** [comment]
I remember DavidBreso's port, the aim was to make ctmouse easier to compile, It was fairly new at the time I found it and unfortunately it didn't work at the time, I don't remember what exactly but I think it complied and mangled the inputs.

Maybe it works now? 

I did also go in to compile the older versions of CTmouse because I remember someone saying they preferred the old ones because of they didn't use as much memory. Technically it would be possible to completely remove unneeded support in ct mouse and make a custom version of it to make this project easier to use under dos.

**Comment by LimeProgramming** [comment]
That was correct. Well done for spotting that. 
BTW if you want to fix an old bug, On line 1005 of utils.c under the MO_MVY_AVERAGE case add the following bit of code 

```      // Avoid a Div by zero err
      if ( mouse_data.mouse_movt_ticker == 0 ) { 
        retpkt.x = 0;
        retpkt.y = 0;
        break; 
      }
```

and break out this line ` mouse_data.mouse_movt_ticker = 0; // Reset mouse poll count` from line 948 of the same file to outside the switch and before the return. 


That should patch an issue where if you have the mouse set to average movement type and you plug out the usb mouse the cursor flys off screen, try it in doom and you'll spin quickly on the spot. I think that's all of it, it's patched in the Keyboard version of the project already but that version was made to totally replace this and keep support for the older hardware.

**Comment by sweetlilmre** [comment]
Thanks! I've been working on replacement firmware for necroware's PS2 to Serial adapter and added in the wheel mouse compatibility, so that's why I knew about the differences in 3rd button bits :) If this firmware is going to be EOL should I be switching to the newer keyboard / mouse one? (sent you a PR for the fixes above anyway)

**Comment by LimeProgramming** [comment]
Thanks for that. You can if you want to, but I'm not sure I'll ever really finish it. I know there's not much else that needs doing, like fixing the XT keyboard support and implement a few more of the ps2 commands. I think most of the simple ones have been done. I think the mouse side of that adapter is largely the same but with some elements changed or rewritten just to work better with the keyboard side of it. 

I'd probably have XT support done if I had an XT machine to test with. Even looked into making an XT machine. 

PS/2 to serial mouse adapter was the basis of this project but I wanted to support usb mice since ps/2 mice are dying off. Might be worthwhile if someone changed the MCU to something with better usb host support. Maybe a teensy? Not sure really. 

Eitherway, if anything in this project is useful to you, take it.

**Pull request merged**
